//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCrypt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestCrypt.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred applying the keyfiles..
        /// </summary>
        internal static string ApplyKeyfilesFailed {
            get {
                return ResourceManager.GetString("ApplyKeyfilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        internal static string Disk {
            get {
                return ResourceManager.GetString("Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 64-bit operating system which requires signed drivers has been detected. Click here to get further information..
        /// </summary>
        internal static string DriverSignatureEnforcement {
            get {
                return ResourceManager.GetString("DriverSignatureEnforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit TestCrypt?.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset (in bytes).
        /// </summary>
        internal static string HeaderPropertyEncryptedAreaOffset {
            get {
                return ResourceManager.GetString("HeaderPropertyEncryptedAreaOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Alogrithm.
        /// </summary>
        internal static string HeaderPropertyEncryptionAlgorithm {
            get {
                return ResourceManager.GetString("HeaderPropertyEncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Version.
        /// </summary>
        internal static string HeaderPropertyHeaderVersion {
            get {
                return ResourceManager.GetString("HeaderPropertyHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Mode.
        /// </summary>
        internal static string HeaderPropertyOperationMode {
            get {
                return ResourceManager.GetString("HeaderPropertyOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKCS#5 PRF.
        /// </summary>
        internal static string HeaderPropertyPkcs5Prf {
            get {
                return ResourceManager.GetString("HeaderPropertyPkcs5Prf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required TrueCrypt Version.
        /// </summary>
        internal static string HeaderPropertyRequiredTrueCryptVersion {
            get {
                return ResourceManager.GetString("HeaderPropertyRequiredTrueCryptVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Size (in bytes).
        /// </summary>
        internal static string HeaderPropertySectorSize {
            get {
                return ResourceManager.GetString("HeaderPropertySectorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (in bytes).
        /// </summary>
        internal static string HeaderPropertySize {
            get {
                return ResourceManager.GetString("HeaderPropertySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string HeaderPropertyType {
            get {
                return ResourceManager.GetString("HeaderPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string HeaderPropertyTypeHidden {
            get {
                return ResourceManager.GetString("HeaderPropertyTypeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string HeaderPropertyTypeNormal {
            get {
                return ResourceManager.GetString("HeaderPropertyTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;US&quot; keyboard layout cannot be selected. Be aware that only input languages configured in the Windows® Control Panel can be used..
        /// </summary>
        internal static string KeyboardLayoutNotAvailable {
            get {
                return ResourceManager.GetString("KeyboardLayoutNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take effect with the next start of TestCrypt..
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the TestCrypt driver has failed with error code 0x{0:X8}: {1}..
        /// </summary>
        internal static string LoadTestCryptDriverFailed {
            get {
                return ResourceManager.GetString("LoadTestCryptDriverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load TestCrypt driver.
        /// </summary>
        internal static string LoadTestCryptDriverFailedTitle {
            get {
                return ResourceManager.GetString("LoadTestCryptDriverFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the DLL-file &quot;TrueCrypt.dll&quot; or &quot;TrueCrypt-x64.dll&quot;..
        /// </summary>
        internal static string LoadTrueCryptDllFailed {
            get {
                return ResourceManager.GetString("LoadTrueCryptDllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening the TestCrypt driver has failed with error code 0x{0:X8}: {1}..
        /// </summary>
        internal static string OpenTestCryptDriverFailed {
            get {
                return ResourceManager.GetString("OpenTestCryptDriverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current settings will be lost. Do you really want to return to previous view?.
        /// </summary>
        internal static string PageBackWarning {
            get {
                return ResourceManager.GetString("PageBackWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or not a TrueCrypt header..
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you have entered contains the following character(s) which cannot be stored using ASCII encoding: {0}. A TrueCrypt volume cannot be created using this password using a current version of TrueCrypt.\n\nDo you really want to continue using this password?.
        /// </summary>
        internal static string PasswordWithInvalidCharacter {
            get {
                return ResourceManager.GetString("PasswordWithInvalidCharacter", resourceCulture);
            }
        }
    }
}
